# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
pro: true
project_name: goreleaser-mcp

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
  description: GoReleaser MCP server
  homepage: https://goreleaser.com/mcp
  license: MIT
  maintainers:
    - Carlos Alexandro Becker <carlos@becker.software>

checksum:
  name_template: "checksums.txt"

docker_digest:
  name_template: "digest.txt"

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    vendor: GoReleaser
    section: utils
    mtime: "{{ .CommitDate }}"
    contents:
      - src: ./LICENSE.md
        dst: /usr/share/doc/goreleaser/copyright
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

dockers_v2:
  - images:
      - "ghcr.io/goreleaser/mcp"
    tags:
      - latest
      - "{{ .Version }}"
    labels:
      "org.opencontainers.image.description": "{{.Metadata.Description}}"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/goreleaser/mcp"
      "io.modelcontextprotocol.server.name": "io.github.goreleaser/mcp"
    annotations:
      "org.opencontainers.image.description": "{{.Metadata.Description}}"

homebrew_casks:
  - name: mcp
    repository:
      owner: goreleaser
      name: homebrew-tap
    url:
      verified: github.com/goreleaser/mcp/releases/download

winget:
  - name: mcp
    publisher: goreleaser
    repository:
      owner: goreleaser
      name: winget-pkgs
      branch: "mcp-{{.Version}}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

aurs:
  - private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/goreleaser-mcp-bin.git"
    package: |-
      # bin
      install -Dm755 "./goreleaser-mcp" "${pkgdir}/usr/bin/goreleaser-mcp"

      # license
      install -Dm644 "./LICENSE.md" "${pkgdir}/usr/share/licenses/goreleaser-mcp/LICENSE"

npms:
  - name: "@goreleaser/mcp"
    repository: https://github.com/goreleaser/mcp
    bugs: https://github.com/goreleaser/mcp/issues
    extra:
      "mcpName": "io.github.goreleaser/mcp"
    keywords:
      - goreleaser
      - mcp

sboms:
  - artifacts: archive

universal_binaries:
  - replace: false

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    artifacts: checksum
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes

docker_signs:
  - cmd: cosign
    artifacts: manifests
    args:
      - "sign"
      - "${artifact}@${digest}"
      - --yes

changelog:
  sort: asc
  use: git
  divider: "---"
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: update$"
      - "^chore: docs$"
      - "^docs: update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: auto-update generated files$"
      - "^chore: update schema$"
      - "^chore: schema update$"
      - "^chore\\(deps\\): "
      - "^(build|ci): "
      - "^(build|ci)\\(.*\\): "
      - "merge conflict"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor|refactory|test)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

release:
  name_template: "{{ .Tag }}"
  footer: |
    **Full Changelog**: https://github.com/goreleaser/mcp/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}

    {{ if not .IsNightly }}
    ## Helping out

    This release is only possible thanks to **all** the support of some **awesome people**!

    Want to be one of them?
    You can [sponsor](https://goreleaser.com/sponsors/), get a [Pro License](https://goreleaser.com/pro) or [contribute with code](https://goreleaser.com/contributing).

    ## Where to go next?

    * Find examples and commented usage of all options in our [website](https://goreleaser.com/intro/).
    * Reach out on [Discord](https://discord.gg/RGEBtg8vQ6) and [Twitter](https://twitter.com/goreleaser)!

    <a href="https://goreleaser.com"><img src="https://raw.githubusercontent.com/goreleaser/artwork/master/opencollective-header.png" with="100%" alt="GoReleaser logo"></a>
    {{ end }}

furies:
  - account: goreleaser
    disable: "{{ .IsNightly }}"
