# https://taskfile.dev

version: "3"

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org,direct

tasks:
  default:
    cmds:
      - task: update
      - task: sync
  update:
    desc: update goreleaser-pro
    cmds:
      - go get github.com/goreleaser/goreleaser-pro@latest
      - go mod tidy
  sync:
    desc: Sync docs
    sources:
      - ../goreleaser/www/docs/
    generates:
      - ./pkg/config/
    cmds:
      - mkdir -p docs
      - cp -rf ../goreleaser/www/docs/customization ./docs/
      - cp -rf ../goreleaser/www/docs/deprecations.md ./docs/
